### ISSUE TITLE
WHAT DO WE NEED TO DO TO GET GOING AGAIN???

### ISSUE THREAD

**Issue by skistaddy** [Newawe/newawe#55]
Ok, everybody. We need to get Newawe running again. What do we need to do to do it? I've got plenty of time as of now, and I can contribute as much as possible. I now know PHP, so that will help. What do we need to do? Do we need DBs? I for one, need the creds to the site. Whoever has em, mail em to me at baranjskistad@gmail.com
# List of stuff to do
- Example

**Comment by ghost** [comment]
ugh... why must you use WT*?

**Comment by skistaddy** [comment]
Sorry, just for emphasis. Dylan did not pay for our domain just to let it go to waste.

**Comment by as-com** [comment]
???

If you must use PHP, please use a proper framework like Laravel.

**Comment by skistaddy** [comment]
ooookkkkkk... I originally liked using Node.js, but this time - if we do use it again - I think we should use a different framework, like Express

**Comment by robinp7720** [comment]
I would agree with @as-com, while I did make the basic framework for this project, it's simply easier and more reliable to use a mature framework such as Laravel, Zend, Slim, CakePHP etc.

For nodejs express certainly is a possibility but solutions such as featherjs include authentication managers and other useful feature. Other frameworks such as meteor or meatier.

Secondly, you need a plan. a concrete plan of what the application should be, and should do. 

Thirdly, do not allow anyone to push directly into the repo. Even yourself. Everyone who contributes must fork the repo and develop in their own repo. When they have implemented/fixed/added something which has to do with the plan, then they can PR it. When the code is of good quality and it contributes something from the plan you made earlier, then you can accept it. If the PR has nothing to do with achieving the plan, then deny it.

Why not develop directly in the master branch on the main repo?
Because then, people push and commit and break someone else's work.

**Comment by jeandrek** [comment]
Can you get rid of the "... changed the title from ... to  ..."?

**Comment by CosmicWebServices** [comment]
I love the concept but maybe this could integrate with other services like github

**Comment by JordanB-1337** [comment]
@herohamp You hear that? It's not as dead as you said it was!

**Comment by skistaddy** [comment]
@Jonathan50 I could delete the issue and recreate it.
